CREATE TABLE IF NOT EXISTS Tracks (
    "id" UUID NOT NULL PRIMARY KEY,
    "arrival" VARCHAR(255) NOT NULL,
    "departure" VARCHAR(255) NOT NULL,
    "long_flight" INTEGER NOT NULL,
    "created_at" TIMESTAMP(0) WITH TIME zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(0) WITH TIME zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" BOOLEAN NOT NULL DEFAULT false
);