name: Tests Ticket Service
on:
  pull_request:
    branches:
      - master

defaults:
  run:
    working-directory: ticket-service

jobs:
  build:
    runs-on: ubuntu-latest

  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19.x'
      - name: Get dependencies
        run: |
          go get -v -t -d ./...        
      - name: Test with the Go CLI
        run: go test -v ./...