name: CI
on:
  pull_request:
    branches:
      - master

jobs:
  jobs1:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ticket-service

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.16.x'
      - name: Get dependencies
        run: |
          go get -v -t -d ./...        
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test